var five = 5;
var ten = 10;
console.log("\nTest 1: five is equal to 5?");
console.log(five == 5);
console.log("\nTest 2: Ten is equal to 10?");
console.log(ten == 10);
console.log("\nTest 3: 5 is not equal to 10?");
console.log(five != 10);
console.log("\nTest 4: 10 is greater than 5?");
console.log(10 > 5);
console.log("\nTest 5: 77 is smaller than 111?");
console.log(77 < 111);
console.log("\nTest 6: 10 is smaller than 5?");
console.log(10 < 5);
console.log("\nTest 7: 10 is equal to 5?");
console.log(ten == 5);
console.log("\ntest 8: 10 is not equal to 10?");
console.log(10 != 10);
console.log("\nTest 9: five is greater than 10?");
console.log(five > 5);
console.log("\nTest 10: 100 is smaller than 50?");
console.log(100 < 50);
